//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace individ.sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainInfo
    {
        public int ID { get; set; }
        public Nullable<int> IDNameWork { get; set; }
        public Nullable<int> IDFullName { get; set; }
        public Nullable<int> IDReadiness { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Work Work { get; set; }
        public virtual WorkInfo WorkInfo { get; set; }
    }
}
