//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace individ.sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkInfo()
        {
            this.MainInfo = new HashSet<MainInfo>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfComplite { get; set; }
        public System.DateTime PlannedDateFoComplite { get; set; }
        public int Laboriousness { get; set; }
        public int Readiness { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainInfo> MainInfo { get; set; }
    }
}
